### ISSUE TITLE
Can't seem to get docker image working

### ISSUE THREAD

**Issue by TheYsconator** [matrix-construct/construct#196]
Hey there! I'm trying to set-up a local instance of Construct using Docker, but I've been unable to get it working, so far.

I'm using the following files to set-up a minimal-type installation, but the image exits immediately with code 0. No logs are written.

I expect to be missing some configuration or settings that I should pass, but so far I haven't been able to figure out which exactly. Can you take a look at the files below and let me know what I should add/change in order to set up Construct locally?

.env file:
```
STATE_DIRECTORY=/var/db/construct/
```

docker-compose.yml
```
version: '3.3'

services:
  construct:
    image: jevolk/construct:ubuntu-22.04-full-built-clang-14-amd64-avx
    env_file: .env
    volumes:
      - ./construct_data/:/var/db/construct/
```
